"""initial
Revision ID: 0001_initial
Revises: 
Create Date: 2026-04-24
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001_initial'
down_revision=None
branch_labels=None
depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('email',sa.String(255),nullable=False),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',sa.String(32),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('is_locked',sa.Boolean(),nullable=False),sa.Column('failed_login_count',sa.Integer(),nullable=False),sa.Column('twofa_secret',sa.String(64)),sa.Column('twofa_enabled',sa.Boolean(),nullable=False),sa.Column('trader_balance',sa.Numeric(18,2),nullable=False,server_default='0'),sa.Column('trader_hold',sa.Numeric(18,2),nullable=False,server_default='0'),sa.Column('trader_traffic_priority',sa.Integer(),nullable=False,server_default='50'),sa.Column('trader_assigned_merchants',postgresql.JSON(),nullable=False,server_default='[]'),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index('ix_users_email','users',['email'],unique=True); op.create_index('ix_users_role','users',['role'])
    op.create_table('merchants',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('owner_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False,unique=True),sa.Column('name',sa.String(160),nullable=False),sa.Column('webhook_url',sa.String(500)),sa.Column('ip_whitelist',postgresql.JSON(),nullable=False),sa.Column('sandbox_mode',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('api_keys',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('merchants.id',ondelete='CASCADE'),nullable=False),sa.Column('api_key',sa.String(80),nullable=False,unique=True),sa.Column('secret_hash',sa.String(255),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('mode',sa.String(16),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index('ix_api_keys_api_key','api_keys',['api_key']); op.create_index('ix_api_keys_merchant_id','api_keys',['merchant_id'])
    op.create_table('balances',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('merchants.id',ondelete='CASCADE'),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('available',sa.Numeric(18,2),nullable=False),sa.Column('frozen',sa.Numeric(18,2),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('merchant_id','currency',name='uq_balance_merchant_currency')); op.create_index('ix_balances_merchant_id','balances',['merchant_id'])
    op.create_table('requisites',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('trader_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('owner_name',sa.String(160),nullable=False),sa.Column('full_name',sa.String(160)),sa.Column('method',sa.String(32),nullable=False),sa.Column('value_encrypted',sa.Text(),nullable=False),sa.Column('bank_name',sa.String(100)),sa.Column('automation_id',sa.String(120)),sa.Column('last4',sa.String(4)),sa.Column('request_count',sa.Integer(),nullable=False,server_default='10'),sa.Column('timeframe',sa.String(16),nullable=False,server_default='час'),sa.Column("success_delay_minutes",sa.Integer(),nullable=False,server_default="0"),sa.Column("simultaneous_limit",sa.Integer(),nullable=False,server_default="1"),sa.Column('min_check',sa.Numeric(18,2),nullable=False,server_default='100'),sa.Column('max_check',sa.Numeric(18,2),nullable=False,server_default='150000'),sa.Column('enabled',sa.Boolean(),nullable=False),sa.Column('daily_limit',sa.Numeric(18,2),nullable=False),sa.Column('operation_limit',sa.Integer(),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('usage_count',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('deposits',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('merchants.id',ondelete='CASCADE'),nullable=False),sa.Column('external_id',sa.String(128),nullable=False),sa.Column('amount',sa.Numeric(18,2),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('method',sa.String(32),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('requisites_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('requisites.id')),sa.Column('client_ip',sa.String(64)),sa.Column('metadata_json',postgresql.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('merchant_id','external_id',name='uq_deposit_merchant_external')); op.create_index('ix_deposits_merchant_id','deposits',['merchant_id']); op.create_index('ix_deposits_status','deposits',['status'])
    op.create_table('payouts',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('merchants.id',ondelete='CASCADE'),nullable=False),sa.Column('external_id',sa.String(128),nullable=False),sa.Column('amount',sa.Numeric(18,2),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('method',sa.String(32),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('destination',sa.String(255),nullable=False),sa.Column('metadata_json',postgresql.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('merchant_id','external_id',name='uq_payout_merchant_external')); op.create_index('ix_payouts_merchant_id','payouts',['merchant_id']); op.create_index('ix_payouts_status','payouts',['status'])
    for name in ['ledger_entries','appeals','appeal_messages','sms_messages','webhook_events','api_request_logs','audit_logs','fee_rules','limit_rules','blacklist']:
        pass
    op.create_table('ledger_entries',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('merchants.id',ondelete='CASCADE'),nullable=False),sa.Column('operation_id',postgresql.UUID(as_uuid=True)),sa.Column('entry_type',sa.String(32),nullable=False),sa.Column('amount',sa.Numeric(18,2),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('description',sa.String(500),nullable=False),sa.Column('idempotency_key',sa.String(128),unique=True),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('appeals',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('operation_type',sa.String(32),nullable=False),sa.Column('operation_id',postgresql.UUID(as_uuid=True),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('created_by',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id')),sa.Column('decision',sa.String(64)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('appeal_messages',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('appeal_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('appeals.id',ondelete='CASCADE'),nullable=False),sa.Column('author_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id')),sa.Column('message',sa.Text(),nullable=False),sa.Column('attachment_path',sa.String(500)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('sms_messages',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('provider_message_id',sa.String(128),nullable=False,unique=True),sa.Column('sender',sa.String(128),nullable=False),sa.Column('body',sa.Text(),nullable=False),sa.Column('parsed_amount',sa.Numeric(18,2)),sa.Column('linked_deposit_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('deposits.id')),sa.Column('processed',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('webhook_events',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('merchants.id',ondelete='CASCADE'),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('payload',postgresql.JSON(),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('attempts',sa.Integer(),nullable=False),sa.Column('last_error',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('api_request_logs',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True)),sa.Column('method',sa.String(16),nullable=False),sa.Column('path',sa.String(500),nullable=False),sa.Column('ip',sa.String(64),nullable=False),sa.Column('status_code',sa.Integer(),nullable=False),sa.Column('request_id',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('audit_logs',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('actor_id',postgresql.UUID(as_uuid=True)),sa.Column('action',sa.String(160),nullable=False),sa.Column('target_type',sa.String(80),nullable=False),sa.Column('target_id',sa.String(128)),sa.Column('ip',sa.String(64)),sa.Column('details',postgresql.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('fee_rules',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True)),sa.Column('method',sa.String(32),nullable=False),sa.Column('percent',sa.Numeric(8,4),nullable=False),sa.Column('fixed',sa.Numeric(18,2),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('limit_rules',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('merchant_id',postgresql.UUID(as_uuid=True)),sa.Column('method',sa.String(32)),sa.Column('min_amount',sa.Numeric(18,2),nullable=False),sa.Column('max_amount',sa.Numeric(18,2),nullable=False),sa.Column('daily_amount',sa.Numeric(18,2),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table('blacklist',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('kind',sa.String(32),nullable=False),sa.Column('value',sa.String(255),nullable=False),sa.Column('reason',sa.String(500),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('kind','value',name='uq_blacklist_kind_value'))

def downgrade():
    for t in ['blacklist','limit_rules','fee_rules','audit_logs','api_request_logs','webhook_events','sms_messages','appeal_messages','appeals','ledger_entries','payouts','deposits','requisites','balances','api_keys','merchants','users']:
        op.drop_table(t)
