from app.core.enums import DepositStatus, PayoutStatus, Role


ROLE_PERMISSIONS = {
    Role.superadmin.value: [
        'users.manage_all',
        'merchants.manage_all',
        'operators.manage_all',
        'operations.confirm',
        'operations.complete',
        'requisites.manage_all',
        'appeals.resolve',
        'sms.confirm',
        'risk.manage',
        'fees.manage',
        'limits.manage',
        'blacklist.manage',
        'audit.read',
        'reports.export',
        'teamlead.manage',
        'teamlead.finance',
        'teamlead.create',
        'teamlead.read_basic',
        'platform_wallet.manage',
        'platform_wallet.read',
        'ai_office.manage',
    ],
    Role.admin.value: [
        'users.manage_operational',
        'merchants.manage_all',
        'operators.manage_all',
        'operations.confirm',
        'operations.complete',
        'requisites.manage_all',
        'appeals.resolve',
        'sms.confirm',
        'risk.manage',
        'fees.manage',
        'limits.manage',
        'blacklist.manage',
        'reports.export',
        'teamlead.create',
        'teamlead.read_basic',
        'platform_wallet.read',
    ],
    Role.support.value: [
        'operations.read_all',
        'operators.read',
        'appeals.reply',
        'risk.read',
        'webhooks.retry',
    ],
    Role.teamlead.value: [
        'teamlead.read_own',
        'teamlead.settlement.create_own',
    ],
    Role.merchant.value: [
        'merchant_api.use',
        'wallet.read_own',
        'operations.read_own',
        'appeals.create_own',
        'webhooks.retry_own',
    ],
    Role.operator.value: [
        'requisites.manage_own',
        'operations.confirm',
        'sms.confirm',
        'appeals.reply',
        'platform_wallet.read',
    ],
    Role.trader.value: [
        'requisites.manage_own',
        'operations.confirm',
        'sms.confirm',
        'appeals.reply',
        'platform_wallet.read',
    ],
}


BUSINESS_RULES = {
    'deposit_status_flow': {
        DepositStatus.created.value: [DepositStatus.pending.value, DepositStatus.cancelled.value, DepositStatus.expired.value],
        DepositStatus.pending.value: [DepositStatus.paid.value, DepositStatus.failed.value, DepositStatus.cancelled.value, DepositStatus.expired.value, DepositStatus.appeal_opened.value],
        DepositStatus.appeal_opened.value: [DepositStatus.pending.value, DepositStatus.paid.value, DepositStatus.failed.value, DepositStatus.cancelled.value],
        DepositStatus.paid.value: [],
        DepositStatus.failed.value: [],
        DepositStatus.expired.value: [],
        DepositStatus.cancelled.value: [],
    },
    'payout_status_flow': {
        PayoutStatus.created.value: [PayoutStatus.pending.value, PayoutStatus.cancelled.value],
        PayoutStatus.pending.value: [PayoutStatus.processing.value, PayoutStatus.failed.value, PayoutStatus.cancelled.value, PayoutStatus.rejected.value, PayoutStatus.appeal_opened.value],
        PayoutStatus.processing.value: [PayoutStatus.completed.value, PayoutStatus.failed.value, PayoutStatus.cancelled.value, PayoutStatus.rejected.value, PayoutStatus.appeal_opened.value],
        PayoutStatus.appeal_opened.value: [PayoutStatus.pending.value, PayoutStatus.processing.value, PayoutStatus.completed.value, PayoutStatus.failed.value, PayoutStatus.cancelled.value, PayoutStatus.rejected.value],
        PayoutStatus.completed.value: [],
        PayoutStatus.failed.value: [],
        PayoutStatus.cancelled.value: [],
        PayoutStatus.rejected.value: [],
    },
    'default_fees': {
        'sbp': {'percent': '1.5000', 'fixed': '0.00'},
        'c2c': {'percent': '2.0000', 'fixed': '10.00'},
        'mobile_commerce': {'percent': '3.0000', 'fixed': '0.00'},
        'mobile': {'percent': '3.0000', 'fixed': '0.00'},
    },
    'default_limits': {
        'min_amount': '100.00',
        'max_amount': '150000.00',
        'daily_amount': '1000000.00',
    },
    'settlement': {
        'deposit_credit': 'Merchant balance is credited with net amount: gross deposit minus fee.',
        'payout_hold': 'Payout amount is moved from available balance to frozen balance on payout creation.',
        'payout_completion': 'Frozen amount is debited when payout is completed.',
    },
}
